// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: user.proto

package userclient

import (
	"context"

	"go-zero-im/rpc/user"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	UserReq = user.UserReq
	UserRes = user.UserRes

	User interface {
		GetUser(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserRes, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUser(ctx context.Context, in *UserReq, opts ...grpc.CallOption) (*UserRes, error) {
	client := user.NewUserClient(m.cli.Conn())
	return client.GetUser(ctx, in, opts...)
}
