version: "3"

services:
  etcd:
    build:
      context: ./
      dockerfile: dockerfile_etcd
    container_name: etcd
    ports:
      - "2379:2379"
      - "2380:2380"
    environment:
      - ETCD_ENABLE_V2=true
      - ALLOW_NONE_AUTHENTICATION=yes
      - ETCD_ADVERTISE_CLIENT_URLS=http://etcd:2379
      - ETCD_LISTEN_CLIENT_URLS=http://0.0.0.0:2379
      - ETCD_NAME=etcd
    volumes:
      - ./etcd/data:/bitnami/etcd/data
      - ./etcd/logs:/bitnami/etcd/logs
    networks:
      go_zero_im_net:

  user-rpc:
    image: user-rpc
    container_name: user-rpc
    ports:
      - "8080:8080"
    links:
      - etcd
    # 由于启动时无需的，所以指定在etcd启动后启动
    depends_on:
      - etcd
    networks:
      go_zero_im_net:

  user-api:
    image: user-api
    container_name: user-api
    ports:
      - "8888:8888"
    links:
      - etcd
    # 由于启动时无需的，所以指定在etcd启动后启动
    depends_on:
      - user-rpc
      - etcd
    networks:
      go_zero_im_net:

networks:
  go_zero_im_net:
    driver: bridge