// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.5
// Source: user.proto

package server

import (
	"context"

	"go-zero-im/rpc/internal/logic"
	"go-zero-im/rpc/internal/svc"
	"go-zero-im/rpc/user"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) GetUser(ctx context.Context, in *user.UserReq) (*user.UserRes, error) {
	l := logic.NewGetUserLogic(ctx, s.svcCtx)
	return l.GetUser(in)
}

// 添加 CreateUser 来测试在 go-zero 中使用mysql
func (s *UserServer) CreateUser(ctx context.Context, in *user.CreateReq) (*user.CreateRes, error) {
	l := logic.NewCreateUserLogic(ctx, s.svcCtx)
	return l.CreateUser(in)
}
